imports:
    - { resource: parameters.yml }

services:
    # OpenWeatherMap
    nfq_weather.parser.open_weather_map:
        class: Nfq\WeatherBundle\Parser\OpenWeatherMapParser
        public: false

    nfq_weather.provider.open_weather_map:
        class: Nfq\WeatherBundle\Provider\OpenWeatherMapProvider
        arguments: ["@nfq_weather.parser.open_weather_map", "%openweathermap_api_key%"]
#        aliases: nfq_weather

    # Yahoo
    nfq_weather.parser.yahoo:
        class: Nfq\WeatherBundle\Parser\YahooParser
        public: false

    nfq_weather.provider.yahoo:
        class: Nfq\WeatherBundle\Provider\YahooProvider
        arguments: ["@nfq_weather.parser.yahoo"]

    # Delegating
    nfq_weather.parser.yahoo:
        class: Nfq\WeatherBundle\Parser\YahooParser
        public: false

    nfq_weather.provider.delegating:
        class: Nfq\WeatherBundle\Provider\DelegatingProvider
        arguments: ["%providers%"]
