imports:
    - { resource: parameters.yml }

services:
    # OpenWeatherMap
    nfq_weather.parser.openweathermap:
        class: Nfq\WeatherBundle\Parser\OpenWeatherMapParser
        public: false

    nfq_weather.provider.openweathermap:
        class: Nfq\WeatherBundle\Provider\OpenWeatherMapProvider
        arguments: ["@nfq_weather.parser.openweathermap", "%openweathermap_api_key%"]

    # Yahoo
    nfq_weather.parser.yahoo:
        class: Nfq\WeatherBundle\Parser\YahooParser
        public: false

    nfq_weather.provider.yahoo:
        class: Nfq\WeatherBundle\Provider\YahooProvider
        arguments: ["@nfq_weather.parser.yahoo"]

    # Delegating
    nfq_weather.provider.delegating:
        class: Nfq\WeatherBundle\Provider\DelegatingProvider
        arguments: []

# monolog bundle