imports:
    - { resource: parameters.yml }

services:
#    nfq_weather.example:
#        class: Nfq\WeatherBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    nfq_weather.parser.open_weather_map:
        class: Nfq\WeatherBundle\Parser\OpenWeatherMapParser
        public: false

    nfq_weather.provider.open_weather_map:
        class: Nfq\WeatherBundle\Provider\OpenWeatherMapProvider
        arguments: ["@nfq_weather.parser.open_weather_map", "%openweathermap_api_key%"]
#        alias: nfq_weather
